config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   # we want to see multiple Products
   resources :products do
     resources :order_items
   end


   # we want the user to order multiple times
   resources :orders

   # we only want a user to see One cart
   resource :cart
   

   get "info", to: "pages#info"

   root "pages#home"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :order_items

  def total_quantity
    @count = 0

    order_items.all.each do |item|
      @count = @count + item.quantity
    end

    @count
  end

  def total_price
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price * item.quantity
    end

    @total
  end

  def total_price_in_dollars
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price_in_dollars * item.quantity
    end

    @total
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :country, presence: true

  accepts_nested_attributes_for :order_items




  def add_from_cart(cart)
    cart.order_items.all.each do |item|
      self.order_items.new(product: item.product, quantity: item.quantity)
    end
  end



  def save_and_charge
    # check our data is valid
    # if it is, charge in stripe
    # if it isn't, then return false
    # charge in stripe and save if all good
    if self.valid?

      Stripe::Charge.create(amount: self.total_price, currency: "usd", source: self.stripe_token,
        description: "Order for " + self.email)

       self.save
    else
      # doesn't pass validation
      false
    end

  rescue Stripe::CardError => e

    # this is from stripe
    @message = e.json_body[:error][:message]

    # then add to the model errors
    self.errors.add(:stripe_token, @message)

    #return false to our controller
    false

  end



  def total_price
      @total = 0

      order_items.each do |item|
        @total = @total + item.product.price * item.quantity

      end
      @total
  end



  def total_price_in_dollars
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price_in_dollars * item.quantity
    end

    @total
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :cart, optional: true
  belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :order_items

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true

  mount_uploader :image_1, ProductImageUploader
  mount_uploader :image_2, ProductImageUploader
  mount_uploader :image_3, ProductImageUploader
  mount_uploader :image_4, ProductImageUploader
  mount_uploader :image_5, ProductImageUploader

  def price_in_dollars
    price / 100
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart
  helper_method :current_cart

  def current_cart
    # session[:user_id]
    # if the customer has just landed on the site, give them a band new Cart
    # if they already have one, keep the Cart
    # check sessions[:cart_id]

    if session[:cart_id].present?
      # they already a cart
      @current_cart = Cart.find(session[:cart_id])
    else
      # they don't have a cart
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    # cart is already set up beacuse of application controller
  end



end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    # find the product
    @product = Product.find(params[:product_id])

    # car = @current_cart

    # quantity
    @quantity = form_params[:quantity]

    @current_cart.order_items.create(product: @product, quantity: @quantity)

    # add  a flash message
    flash[:success] = "Thanks for adding to your cart"

    redirect_to product_path(@product)

  end


  def update
    @product = Product.find(params[:product_id])

    @order_item = OrderItem.find(params[:id])

    @order_item.update(form_params)

    flash[:success] = "Thats for updating your cart"

    redirect_to product_path(@product)

  end


  def destroy
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])

    @order_item.delete

    flash[:success] = "Product removed from cart"

    redirect_to cart_path
  end


  def form_params
    params.require(:order_item).permit(:quantity)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @order.add_from_cart(@current_cart)
  end

  def create
    @order = Order.new(form_params)
    @order.add_from_cart(@current_cart)

    if @order.save_and_charge
      reset_session

      flash[:success] = "Order completed"

      OrderMailer.receipt(@order).deliver_now

      redirect_to order_path(@order)
    else
      render "new"
    end

  end

  def form_params
    params.require(:order).permit(:first_name, :last_name, :email, :country, :address_1, :address_2, :city, :postal_code, :stripe_token)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @featured_products = Product.where(is_featured: true)
  end

  def info
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    # if the product is already in the cart
    @order_item = @current_cart.order_items.find_by(product: @product)

    if @order_item.nil?
      # if it does not exit in the cart, then make a cart
      @order_item = @current_cart.order_items.new(product: @product, quantity: 1)
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h2>Cart</h2>

<% if @current_cart.order_items.any? %>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Qty</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @current_cart.order_items.each do |item| %>
      <tr>
          <td>
            <%= image_tag item.product.image_1.thumb, width: "50" %>
            <%= item.product.title %>
          </td>
          <td><%= number_to_currency item.product.price_in_dollars %></td>
          <td>
            <%= simple_form_for [item.product, item] do |f| %>
              <%= f.input :quantity, label: false %>
              <%= f.button :submit, "Update quantity" %>
              <% end %>
          </td>
          <td><%= link_to "Remove", product_order_item_path(item.product, item), method: :delete %>
          </td>
      </tr>
    <% end %>

  </tbody>
</table>

<p>
  Total: <%= number_to_currency @current_cart.total_price_in_dollars %>
</p>

<p>
  <%= link_to "Continue to check", new_order_path %>
</p>

<% else %>
<
<p class="empty">There are no items in your cart</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotherpin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Another Pin Co", root_path %></h1>

      <nav>
        <%= link_to "Shop", products_path %>
        <%= link_to "Info", info_path %>
        <%= link_to cart_path do %>
          Cart (<%= number_to_currency @current_cart.total_price_in_dollars %>)
        <% end %>
      </nav>
    </header>

    <% if flash[:success].present? %>
      <div class="flash-success">
        <%= flash[:success] %>
      </div>
    <% end %>



    <%= yield %>

<footer>
  <p> Copyright 2017
  </p>
</footer>

  </body>
</html>

app/views/orders/new.html.erb
<h1>Checkout</h1>

Total number of items: <%= @order.order_items.size %>

<%= simple_form_for @order do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>

  <%= f.input :email %>

  <%= f.input :country %>
  <%= f.input :address_1 %>
  <%= f.input :address_2 %>
  <%= f.input :city %>
  <%= f.input :postal_code %>

  <div id="card-errors">
    <% @order.errors[:stripe_token].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
  </div>

  <div id="card"></div>

  <%= f.button :submit, "Submit order" %>

<% end %>

<script>
  var stripe = Stripe("<%= Rails.application.secrets.stripe_public_key %>")
  var elements = stripe.elements()

  var card = elements.create("card", { hidePostalCode: true }) 
  card.mount("#card")

  $("form.new_order").on("submit", function (ev) {
    ev.preventDefault()

    stripe.createToken(card).then(function (result) {
      if (result.error) {
        $("#card-errors").html(result.error.message)
      } else {
        $("form.new_order").append("<input type=hidden name='order[stripe_token]' value=" + result.token.id + ">")
        $("form.new_order").get(0).submit()
      }
    })
  })
</script>

app/views/orders/show.html.erb
<h1>Thanks for your order</h1>

<p>Your order has been received</p>

<p>
  <%= link_to "back to home", root_path %>
</p>

<%= @order.first_name %>
<%= @order.city %>

<% @order.order_items.each do |item| %>
  <%= item.product.title %>
<% end %>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<h2>Featured Pins</h2>

<%= render partial: "products/product", collection: @featured_products %>

app/views/pages/info.html.erb
<h1>About Another Pin </h1>

<p>  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/products/_product.html.erb
<div class="product">

<%= link_to product_path(product) do %>
<%= image_tag product.image_1.medium %>
<% end %>

<h3><%= link_to product.title, product_path(product) %></h3>

<p>
  <%= number_to_currency product.price_in_dollars %>
</p>

</div>

app/views/products/index.html.erb
<h2>2017 Collection</h2>

<%= render partial: "product", collection: @products %>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<%= simple_format @product.description %>

<%= simple_form_for [@product, @order_item] do |f| %>
  <%= f.input :quantity %>

  <%= f.button :submit, "Add to cart" %>
<% end %>

<p>
  <%= link_to "Back to all products", products_path %>
</p>